// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcI0yEQh_X_KFqgWB_Jj0tcuwqjJS-1qk',
    appId: '1:508580021259:web:3554970f9992dae73ab30e',
    messagingSenderId: '508580021259',
    projectId: 'app-cripto-ce4ff',
    authDomain: 'app-cripto-ce4ff.firebaseapp.com',
    storageBucket: 'app-cripto-ce4ff.firebasestorage.app',
    measurementId: 'G-YQVBRJDGCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBrXF86wjWvUNl509P08HituI1FqqfEoo',
    appId: '1:508580021259:android:7fcb725a2db6532f3ab30e',
    messagingSenderId: '508580021259',
    projectId: 'app-cripto-ce4ff',
    storageBucket: 'app-cripto-ce4ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFUfTzZxNko9gKlcnsURykJy8Y9E9Cf4Y',
    appId: '1:508580021259:ios:e15f530c9ab0ffe83ab30e',
    messagingSenderId: '508580021259',
    projectId: 'app-cripto-ce4ff',
    storageBucket: 'app-cripto-ce4ff.firebasestorage.app',
    androidClientId: '508580021259-09eop7ncnugbuolg78rld3v9ohgnsvhq.apps.googleusercontent.com',
    iosClientId: '508580021259-33taa9o4n4serdrfv00n3outlfi81aca.apps.googleusercontent.com',
    iosBundleId: 'com.brasilcard.devteste.appCripto',
  );

}